joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.75
    has_jerk_limits: true
    max_jerk: 300.0
  joint2:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 1.875
    has_jerk_limits: true
    max_jerk: 300.0
  joint3:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 2.5
    has_jerk_limits: true
    max_jerk: 300.0
  joint4:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.125
    has_jerk_limits: true
    max_jerk: 300.0
  joint5:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 3.75
    has_jerk_limits: true
    max_jerk: 300.0
 end_effector_joint:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 3.75
    has_jerk_limits: true
    max_jerk: 300.0

